'use strict';

module.exports = {

	HTML_CONTAINER: 'gameContainer',

	SCREEN_SIZE_X: 900,
	SCREEN_SIZE_Y: 675,

	PLAYER_INITIAL_LIVES_COUNT: 5,
	PLAYER_GRAVITY_Y: 100,
	PLAYER_GRAVITY_X: 0,

	CANNON_POWER_HEIGTH_MAX: 100,
	CANNON_POWER_MULTIPLIER: 5,
	CANNON_SECONDS_BEFORE_SHOT: 6

};