'use strict';

module.exports = {

	HTML_CONTAINER: 'gameContainer',

	SCREEN_SIZE_X: 900,
	SCREEN_SIZE_Y: 675,

	PLAYER_ACCELERATION: 20,
	CANNON_POWER_HEIGTH_MAX: 100,
	CANNON_POWER_MULTIPLIER: 1

};